import { createHash } from 'node:crypto';
import { mkdir, readdir, rm, stat } from 'node:fs/promises';
import { createReadStream } from 'node:fs';
import { basename, join, resolve, sep } from 'node:path';
import { getDb } from '@/lib/db/client';
import { config } from '@/lib/config';

/**
 * Backups.
 *
 * A backup is a single SQLite file produced by SQLite's own online backup API,
 * not a file copy. That distinction matters: the database runs in WAL mode, so
 * copying the `.db` file while a write is in flight yields something that may
 * open and may be missing the last transactions. `db.backup()` takes a
 * consistent snapshot of a live database, which is the only way to get a
 * restorable file without stopping the application.
 *
 * Uploaded files are deliberately NOT included. They are already on disk beside
 * the database, they are far larger than it, and bundling them would make the
 * one thing you need in a hurry — the data — slow to produce and slow to move.
 * `docs/DEPLOYMENT.md` states plainly that `data/uploads` must be in the
 * server-level backup too; a backup that silently covers half of what someone
 * assumes it covers is worse than one that says what it holds.
 */

export type BackupFile = {
  name: string;
  sizeBytes: number;
  createdAt: string;
  /** SHA-256 of the file, so a transfer can be verified. */
  checksum: string;
};

export class BackupError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'BackupError';
  }
}

function backupRoot(): string {
  return resolve(process.cwd(), config.storage.backupDir);
}

/** Refuses any name that would escape the backup directory. */
function resolveBackupPath(name: string): string {
  // A backup name is generated by this module and never by a user, but the
  // delete and download paths accept one from a request, so it is checked.
  if (!/^choupotman-\d{8}-\d{6}\.db$/.test(name)) {
    throw new BackupError('Nom de sauvegarde invalide.');
  }
  const root = backupRoot();
  const target = resolve(join(root, name));
  if (target !== root && !target.startsWith(root + sep)) {
    throw new BackupError('Chemin de sauvegarde refusé.');
  }
  return target;
}

/**
 * `choupotman-20260915-014232.db` — sortable, and readable at a glance.
 *
 * Built from the date parts rather than by slicing an ISO string: the separators
 * are not all the same width, so index arithmetic on a stripped timestamp
 * silently produces a name that no longer matches `resolveBackupPath`'s pattern —
 * a file that can be created and then never downloaded or deleted.
 */
function buildName(now = new Date()): string {
  const pad = (value: number) => String(value).padStart(2, '0');
  const date = `${now.getUTCFullYear()}${pad(now.getUTCMonth() + 1)}${pad(now.getUTCDate())}`;
  const time = `${pad(now.getUTCHours())}${pad(now.getUTCMinutes())}${pad(now.getUTCSeconds())}`;
  return `choupotman-${date}-${time}.db`;
}

async function checksumOf(path: string): Promise<string> {
  return new Promise((resolvePromise, reject) => {
    const hash = createHash('sha256');
    const stream = createReadStream(path);
    stream.on('data', (chunk) => hash.update(chunk));
    stream.on('end', () => resolvePromise(hash.digest('hex')));
    stream.on('error', reject);
  });
}

/**
 * Takes a consistent snapshot of the live database.
 *
 * `better-sqlite3`'s `backup()` returns a promise and copies pages while the
 * database keeps serving reads, so nothing has to be locked or stopped.
 */
export async function createBackup(): Promise<BackupFile> {
  const root = backupRoot();
  await mkdir(root, { recursive: true });

  const name = buildName();
  const target = join(root, name);

  await getDb().backup(target);

  const info = await stat(target);
  return {
    name,
    sizeBytes: info.size,
    createdAt: info.mtime.toISOString(),
    checksum: await checksumOf(target),
  };
}

export async function listBackups(): Promise<BackupFile[]> {
  const root = backupRoot();
  let names: string[];
  try {
    names = await readdir(root);
  } catch {
    // No directory yet simply means no backup has been taken.
    return [];
  }

  const files: BackupFile[] = [];
  for (const name of names) {
    if (!name.endsWith('.db')) continue;
    try {
      const info = await stat(join(root, name));
      if (!info.isFile()) continue;
      files.push({
        name,
        sizeBytes: info.size,
        createdAt: info.mtime.toISOString(),
        // Hashing every file on every listing would be wasteful; the checksum is
        // computed on download, where it is actually used.
        checksum: '',
      });
    } catch {
      // A file that vanished between readdir and stat is simply skipped.
    }
  }

  return files.sort((a, b) => b.name.localeCompare(a.name));
}

export async function backupPath(name: string): Promise<string> {
  const target = resolveBackupPath(name);
  const info = await stat(target).catch(() => null);
  if (!info || !info.isFile()) throw new BackupError('Sauvegarde introuvable.');
  return target;
}

export async function deleteBackup(name: string): Promise<void> {
  await rm(resolveBackupPath(name), { force: true });
}

/**
 * Keeps the most recent `keep` backups and removes the rest.
 *
 * Called after each new backup so the directory cannot grow without bound on a
 * schedule nobody is watching.
 */
export async function pruneBackups(keep = 14): Promise<string[]> {
  const files = await listBackups();
  const removed: string[] = [];
  for (const file of files.slice(Math.max(1, keep))) {
    await deleteBackup(file.name).catch(() => undefined);
    removed.push(file.name);
  }
  return removed;
}

/**
 * What a restore involves, stated rather than performed.
 *
 * Restoring cannot be done from inside the running application: the process
 * holds the database open, and swapping the file underneath a live connection is
 * how a half-restored database happens. Overwriting also discards everything
 * recorded since the backup, which is a decision for a person at a terminal with
 * the application stopped — not something to offer behind a button.
 */
export function restoreInstructions(name: string): {
  dbPath: string;
  backupFile: string;
  steps: string[];
} {
  const dbPath = config.db.path;
  const file = join(config.storage.backupDir, basename(name));

  return {
    dbPath,
    backupFile: file,
    steps: [
      'Arrêtez l’application (le processus garde la base ouverte).',
      `Mettez de côté la base actuelle : mv ${dbPath} ${dbPath}.avant-restauration`,
      `Supprimez les journaux WAL restants : rm -f ${dbPath}-wal ${dbPath}-shm`,
      `Remettez la sauvegarde en place : cp ${file} ${dbPath}`,
      'Redémarrez l’application, puis vérifiez la connexion et quelques écrans.',
      'Conservez le fichier .avant-restauration jusqu’à ce que vous soyez certain du résultat.',
    ],
  };
}
